// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.query.sql

package storage

import (
	"context"
)

const getRoom = `-- name: GetRoom :one
SELECT id, name FROM rooms WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
