// api/methods ownership registry (006 C2).
//
// owner ∈ movie | player | sound | key | mouse | system | global | member |
//           castLib | sprite | channel | window | net | creator | top
//
// Built from director_core_objects.txt method summaries (see
// specs/006-api/research.md) + the api/methods file set. The audit test
// asserts: every file in methods/ has an entry,
// the entry matches the `// @owner` header at the top of the file, and the set
// is exactly the files present (no strays).

export const METHODS_OWNERS = {
  abort: "top",
  abs: "top",
  alert: "player",
  appMinimize: "player",
  atan: "top",
  beep: "sound",
  beginRecording: "movie",
  bitAnd: "top",
  bitNot: "top",
  bitOr: "top",
  bitXor: "top",
  breakLoop: "channel",
  browserName: "top",
  build: "top",
  cacheSize: "top",
  call: "top",
  callAncestor: "top",
  callFrame: "top",
  camera: "top",
  castLib: "castLib",
  charToNum: "top",
  chars: "top",
  clearCache: "top",
  color: "creator",
  cos: "top",
  count: "top",
  cursor: "player",
  delay: "movie",
  downloadNetThing: "net",
  duplicate: "member",
  externalEvent: "top",
  externalParamName: "player",
  externalParamValue: "player",
  findEmpty: "castLib",
  findLabel: "movie",
  flashToStage: "top",
  float: "top",
  floatP: "top",
  flushInputEvents: "player",
  getNetText: "net",
  getStreamStatus: "net",
  go: "movie",
  goLoop: "movie",
  goNext: "movie",
  goPrevious: "movie",
  goToFrame: "sprite",
  gotoNetMovie: "net",
  gotoNetPage: "net",
  halt: "player",
  handler: "top",
  handlers: "top",
  hitTest: "top",
  idleLoadDone: "movie",
  ignoreWhiteSpace: "top",
  ilk: "top",
  image: "top",
  insertFrame: "movie",
  integer: "top",
  integerP: "top",
  last: "top",
  lastClick: "player",
  lastEvent: "player",
  length: "top",
  light: "top",
  list: "creator",
  listP: "top",
  log: "top",
  makeList: "top",
  makeSubList: "top",
  marker: "movie",
  max: "top",
  maximize: "window",
  mci: "top",
  member: "member",
  min: "top",
  netAbort: "net",
  netDone: "net",
  netError: "net",
  netLastModDate: "net",
  netMIME: "net",
  netTextResult: "net",
  numToChar: "top",
  objectP: "top",
  offset: "top",
  point: "creator",
  postNetText: "net",
  power: "top",
  preloadNetThing: "net",
  propList: "creator",
  quit: "player",
  random: "top",
  rect: "creator",
  script: "top",
  sin: "top",
  sound: "sound",
  sprite: "sprite",
  sqrt: "top",
  stopEvent: "movie",
  string: "top",
  stringP: "top",
  symbol: "top",
  symbolP: "top",
  tan: "top",
  union: "top",
  value: "top",
  voidP: "top",
  window: "window",
};

export const OWNER_CATEGORIES = Object.freeze([
  "movie", "player", "sound", "key", "mouse", "system", "global",
  "member", "castLib", "sprite", "channel", "window", "net", "creator", "top",
]);

export function ownerOf(methodName) {
  return METHODS_OWNERS[methodName] ?? null;
}